=== gunet/openeclass/modules/course_metadata/courseLooseMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ /* ========================================================================
  ~  * Open eClass
  ~  * E-learning and Course Management System
  ~  * ========================================================================
  ~  * Copyright 2003-2024, Greek Universities Network - GUnet
  ~  *
  ~  * Open eClass is an open platform distributed in the hope that it will
  ~  * be useful (without any warranty), under the terms of the GNU (General
  ~  * Public License) as published by the Free Software Foundation.
  ~  * The full license can be read in "/info/license/license_gpl.txt".
  ~  *
  ~  * Contact address: GUnet Asynchronous eLearning Group
  ~  *                  e-mail: info@openeclass.org
  ~  * ========================================================================
  ~  */
  -->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.openeclass.org"
           xmlns="http://www.openeclass.org"
           elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation>
            /* ========================================================================
            * Open eClass 3.0
            * E-learning and Course Management System
            * ========================================================================
            * Copyright 2003-2013  Greek Universities Network - GUnet
            * A full copyright notice can be read in "/info/copyright.txt".
            * For a full list of contributors, see "credits.txt".
            *
            * Open eClass is an open platform distributed in the hope that it will
            * be useful (without any warranty), under the terms of the GNU (General
            * Public License) as published by the Free Software Foundation.
            * The full license can be read in "/info/license/license_gpl.txt".
            *
            * Contact address: GUnet Asynchronous eLearning Group,
            *                  Network Operations Center, University of Athens,
            *                  Panepistimiopolis Ilissia, 15784, Athens, Greece
            *                  e-mail: info@openeclass.org
            * ======================================================================== */
        </xs:documentation>
    </xs:annotation>

    <!-- definition of primitive types -->
    <xs:simpleType name="t_string">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="t_integer">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="t_positiveInteger">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>

    <xs:simpleType name="t_boolean">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="t_url">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>

    <xs:simpleType name="t_blob">
        <xs:restriction base="xs:base64Binary"/>
    </xs:simpleType>

    <xs:simpleType name="t_dateTime">
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>

    <!-- definition of simple types -->
    <xs:simpleType name="t_level">
        <xs:restriction base="t_string">
            <xs:enumeration value="undergraduate"/>
            <xs:enumeration value="graduate"/>
            <xs:enumeration value="doctoral"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_yearOfStudy">
        <xs:restriction base="t_positiveInteger">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_semester">
        <xs:restriction base="t_positiveInteger">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="7"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="9"/>
            <xs:enumeration value="10"/>
            <xs:enumeration value="11"/>
            <xs:enumeration value="12"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_type">
        <xs:restriction base="t_string">
            <xs:enumeration value="compulsory"/>
            <xs:enumeration value="optional"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_format">
        <xs:restriction base="t_string">
            <xs:enumeration value="slides"/>
            <xs:enumeration value="notes"/>
            <xs:enumeration value="video lectures"/>
            <xs:enumeration value="podcasts"/>
            <xs:enumeration value="audio material"/>
            <xs:enumeration value="multimedia material"/>
            <xs:enumeration value="interactive exercises"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definition of complex types -->
    <xs:complexType name="t_image">
        <xs:simpleContent>
            <xs:extension base="t_blob">
                <xs:attribute name="mime" type="t_string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="t_langString">
        <xs:simpleContent>
            <xs:extension base="t_string">
                <xs:attribute name="lang" type="t_string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="t_indexedString">
        <xs:simpleContent>
            <xs:extension base="t_string">
                <xs:attribute name="index" type="t_integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="t_indexedLangString">
        <xs:simpleContent>
            <xs:extension base="t_langString">
                <xs:attribute name="index" type="t_integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="t_indexedurl">
        <xs:simpleContent>
            <xs:extension base="t_url">
                <xs:attribute name="index" type="t_integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="t_instructor">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="firstName"        type="t_langString"/>
            <xs:element name="middleName"       type="t_langString"/>
            <xs:element name="lastName"         type="t_langString"/>
            <xs:element name="fullName"         type="t_langString"/>
            <xs:element name="email"            type="t_string"/>
            <xs:element name="phone"            type="t_string"/>
            <xs:element name="institution"      type="t_string"/>
            <xs:element name="department"       type="t_string"/>
            <xs:element name="language"         type="t_string"/>
            <xs:element name="moreInformation"  type="t_langString"/>
            <xs:element name="cv"               type="t_string"/>
            <xs:element name="photo"            type="t_image"/>
            <xs:element name="registrationCode" type="t_string"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="t_multimedia">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="title"       type="t_indexedString"/>
            <xs:element name="speaker"     type="t_indexedString"/>
            <xs:element name="subject"     type="t_indexedString"/>
            <xs:element name="description" type="t_indexedString"/>
            <xs:element name="keywords"    type="t_indexedString"/>
            <xs:element name="url"         type="t_indexedurl"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="t_digital">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="url"     type="t_indexedurl"/>
            <xs:element name="library" type="t_indexedString"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="t_material">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="notes"      type="t_indexedString"/>
            <xs:element name="slides"     type="t_indexedString"/>
            <xs:element name="exercises"  type="t_indexedString"/>
            <xs:element name="multimedia" type="t_multimedia"/>
            <xs:element name="other"      type="t_indexedString"/>
            <xs:element name="digital"    type="t_digital"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="t_unit">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="title"       type="t_indexedLangString"/>
            <xs:element name="description" type="t_indexedLangString"/>
            <xs:element name="keywords"    type="t_indexedLangString"/>
            <xs:element name="material"    type="t_material"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="t_course">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="g_courseinfo"/>
            <xs:group ref="g_unit"/>
            <xs:group ref="g_other"/>
            <xs:group ref="g_allocation"/>
        </xs:choice>
    </xs:complexType>

    <!-- definition of groups -->
    <xs:group name="g_courseinfo">
        <xs:choice>
            <xs:element name="instructor"                      type="t_instructor"/>
            <xs:element name="title"                           type="t_langString"/>
            <xs:element name="url"                             type="t_url"/>
            <xs:element name="code"                            type="t_langString"/>
            <xs:element name="level"                           type="t_level"/>
            <xs:element name="yearOfStudy"                     type="t_yearOfStudy"/>
            <xs:element name="semester"                        type="t_semester"/>
            <xs:element name="type"                            type="t_type"/>
            <xs:element name="credithours"                     type="t_integer"/>
            <xs:element name="coTeaching"                      type="t_boolean"/>
            <xs:element name="coTeachingColleagueOpensCourse"  type="t_boolean"/>
            <xs:element name="coTeachingAutonomousDepartment"  type="t_boolean"/>
            <xs:element name="coTeachingDepartmentCreditHours" type="t_integer"/>
            <xs:element name="confirmCurriculum"               type="t_boolean"/>
            <xs:element name="confirmVideolectures"            type="t_boolean"/>
            <xs:element name="videolectures"                   type="t_integer"/>
            <xs:element name="visits"                          type="t_integer"/>
            <xs:element name="hits"                            type="t_integer"/>
            <xs:element name="confirmAMinusLevel"              type="t_boolean"/>
            <xs:element name="confirmALevel"                   type="t_boolean"/>
            <xs:element name="confirmAPlusLevel"               type="t_boolean"/>
            <xs:element name="lastLevelConfirmation"           type="t_dateTime"/>
            <xs:element name="firstCreateDate"                 type="t_dateTime"/>
            <xs:element name="language"                        type="t_langString"/>
            <xs:element name="targetGroup"                     type="t_langString"/>
            <xs:element name="credits"                         type="t_integer"/>
            <xs:element name="description"                     type="t_langString"/>
            <xs:element name="contents"                        type="t_langString"/>
            <xs:element name="objectives"                      type="t_langString"/>
            <xs:element name="keywords"                        type="t_langString"/>
            <xs:element name="coursePhoto"                     type="t_image"/>
            <xs:element name="contentDevelopment"              type="t_langString"/>
            <xs:element name="format"                          type="t_string"/>
            <xs:element name="featuredBooks"                   type="t_langString"/>
            <xs:element name="structure"                       type="t_langString"/>
            <xs:element name="teachingMethod"                  type="t_langString"/>
            <xs:element name="assessmentMethod"                type="t_langString"/>
            <xs:element name="prerequisites"                   type="t_langString"/>
            <xs:element name="literature"                      type="t_langString"/>
            <xs:element name="recommendedComponents"           type="t_langString"/>
            <xs:element name="assignments"                     type="t_langString"/>
            <xs:element name="requirements"                    type="t_langString"/>
            <xs:element name="remarks"                         type="t_langString"/>
            <xs:element name="acknowledgments"                 type="t_langString"/>
        </xs:choice>
    </xs:group>

    <xs:group name="g_unit">
        <xs:choice>
            <xs:element name="numberOfUnits" type="t_integer"/>
            <xs:element name="unit"          type="t_unit"/>
        </xs:choice>
    </xs:group>

    <xs:group name="g_other">
        <xs:choice>
            <xs:element name="eudoxusCode" type="t_string"/>
            <xs:element name="eudoxusURL"  type="t_url"/>
            <xs:element name="kalliposURL" type="t_url"/>
            <xs:element name="thematic"    type="t_langString"/>
            <xs:element name="subthematic" type="t_langString"/>
            <xs:element name="license"     type="t_langString"/>
        </xs:choice>
    </xs:group>

    <xs:group name="g_allocation">
        <xs:choice>
            <xs:element name="institution"            type="t_langString"/>
            <xs:element name="institutionDescription" type="t_langString"/>
            <xs:element name="department"             type="t_langString"/>
            <xs:element name="sector"                 type="t_langString"/>
            <xs:element name="curriculumTitle"        type="t_langString"/>
            <xs:element name="curriculumDescription"  type="t_langString"/>
            <xs:element name="outcomes"               type="t_langString"/>
            <xs:element name="curriculumKeywords"     type="t_langString"/>
            <xs:element name="curriculumLevel"        type="t_level"/>
            <xs:element name="curriculumTargetGroup"  type="t_langString"/>
        </xs:choice>
    </xs:group>

    <!-- ====== root element  ======= -->
    <xs:element name="course" type="t_course"/>

</xs:schema>

=== gunet/openeclass/modules/course_metadata/skeleton.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ /* ========================================================================
  ~  * Open eClass
  ~  * E-learning and Course Management System
  ~  * ========================================================================
  ~  * Copyright 2003-2024, Greek Universities Network - GUnet
  ~  *
  ~  * Open eClass is an open platform distributed in the hope that it will
  ~  * be useful (without any warranty), under the terms of the GNU (General
  ~  * Public License) as published by the Free Software Foundation.
  ~  * The full license can be read in "/info/license/license_gpl.txt".
  ~  *
  ~  * Contact address: GUnet Asynchronous eLearning Group
  ~  *                  e-mail: info@openeclass.org
  ~  * ========================================================================
  ~  */
  -->

<course
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.openeclass.org'
    xsi:schemaLocation='http://www.openeclass.org courseLooseMetadata.xsd'>

    <title lang="el"></title>
    <title lang="en"></title>
    <level></level>
    <description lang="el"></description>
    <description lang="en"></description>
    <contents lang="el"></contents>
    <contents lang="en"></contents>
    <objectives lang="el"></objectives>
    <objectives lang="en"></objectives>
    <thematic>othersubj</thematic>
    <subthematic>othersubsubj</subthematic>
    <prerequisites lang="el"></prerequisites>
    <prerequisites lang="en"></prerequisites>
    <literature lang="el"></literature>
    <literature lang="en"></literature>
    <url></url>
    <license lang="el"></license>
    <license lang="en"></license>
    <confirmAMinusLevel>false</confirmAMinusLevel>
    <confirmALevel>false</confirmALevel>
    <confirmAPlusLevel>false</confirmAPlusLevel>
    <lastLevelConfirmation></lastLevelConfirmation>
    <firstCreateDate></firstCreateDate>
    <confirmCurriculum></confirmCurriculum>
    <confirmVideolectures></confirmVideolectures>
    <videolectures>0</videolectures>
    <visits>0</visits>
    <hits>0</hits>

    <code lang="el"></code>
    <keywords lang="el"></keywords>
    <keywords lang="en"></keywords>
    <coursePhoto mime=""></coursePhoto>
    <contentDevelopment lang="el"></contentDevelopment>
    <contentDevelopment lang="en"></contentDevelopment>
    <format></format>
    <recommendedComponents lang="el"></recommendedComponents>
    <recommendedComponents lang="en"></recommendedComponents>
    <assignments lang="el"></assignments>
    <assignments lang="en"></assignments>
    <requirements lang="el"></requirements>
    <requirements lang="en"></requirements>
    <remarks lang="el"></remarks>
    <remarks lang="en"></remarks>
    <acknowledgments lang="el"></acknowledgments>
    <acknowledgments lang="en"></acknowledgments>


    <instructor>
        <firstName lang="el"></firstName>
        <lastName lang="el"></lastName>

        <firstName lang="en"></firstName>
        <lastName lang="en"></lastName>

        <fullName lang="el"></fullName>
        <fullName lang="en"></fullName>

        <moreInformation lang="el"></moreInformation>
        <moreInformation lang="en"></moreInformation>
        <cv></cv>
        <photo mime=""></photo>
        <registrationCode></registrationCode>
    </instructor>

    <coTeaching></coTeaching>
    <coTeachingColleagueOpensCourse></coTeachingColleagueOpensCourse>
    <coTeachingAutonomousDepartment></coTeachingAutonomousDepartment>
    <coTeachingDepartmentCreditHours></coTeachingDepartmentCreditHours>


    <curriculumLevel></curriculumLevel>
    <institution>otherinst</institution>
    <department lang="el"></department>
    <department lang="en"></department>
    <language lang="el"></language>
    <language lang="en"></language>

    <yearOfStudy></yearOfStudy>
    <semester></semester>
    <type></type>
    <credithours></credithours>
    <credits></credits>
    <institutionDescription lang="el"></institutionDescription>
    <institutionDescription lang="en"></institutionDescription>
    <curriculumTitle lang="el"></curriculumTitle>
    <curriculumTitle lang="en"></curriculumTitle>
    <curriculumDescription lang="el"></curriculumDescription>
    <curriculumDescription lang="en"></curriculumDescription>
    <outcomes lang="el"></outcomes>
    <outcomes lang="en"></outcomes>
    <curriculumKeywords lang="el"></curriculumKeywords>
    <curriculumKeywords lang="en"></curriculumKeywords>
    <sector lang="el"></sector>
    <sector lang="en"></sector>
    <targetGroup lang="el"></targetGroup>
    <targetGroup lang="en"></targetGroup>
    <curriculumTargetGroup lang="el"></curriculumTargetGroup>
    <curriculumTargetGroup lang="en"></curriculumTargetGroup>
    <featuredBooks lang="el"></featuredBooks>
    <featuredBooks lang="en"></featuredBooks>
    <structure lang="el"></structure>
    <structure lang="en"></structure>
    <teachingMethod lang="el"></teachingMethod>
    <teachingMethod lang="en"></teachingMethod>
    <assessmentMethod lang="el"></assessmentMethod>
    <assessmentMethod lang="en"></assessmentMethod>
    <eudoxusCode></eudoxusCode>
    <eudoxusURL></eudoxusURL>
    <kalliposURL></kalliposURL>


    <numberOfUnits></numberOfUnits>
    <unit>
        <title></title>
        <description></description>
        <keywords></keywords>
        <material>
            <notes></notes>
            <slides></slides>
            <exercises></exercises>
            <multimedia>
                <title></title>
                <speaker></speaker>
                <subject></subject>
                <description></description>
                <keywords></keywords>
                <url></url>
            </multimedia>
            <other></other>
            <digital>
                <url></url>
                <library></library>
            </digital>
        </material>
    </unit>
</course>

=== gunet/openeclass/modules/course_metadata/sampleCourseMetadata.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ /* ========================================================================
  ~  * Open eClass
  ~  * E-learning and Course Management System
  ~  * ========================================================================
  ~  * Copyright 2003-2024, Greek Universities Network - GUnet
  ~  *
  ~  * Open eClass is an open platform distributed in the hope that it will
  ~  * be useful (without any warranty), under the terms of the GNU (General
  ~  * Public License) as published by the Free Software Foundation.
  ~  * The full license can be read in "/info/license/license_gpl.txt".
  ~  *
  ~  * Contact address: GUnet Asynchronous eLearning Group
  ~  *                  e-mail: info@openeclass.org
  ~  * ========================================================================
  ~  */
  -->

<course
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.openeclass.org'
    xsi:schemaLocation='http://www.openeclass.org courseLooseMetadata.xsd'>

    <instructor>
        <firstName lang="el">Διδάσκων1</firstName>
        <firstName lang="en">Instructor1</firstName>

        <lastName lang="el">Διδάσκων1</lastName>
        <lastName lang="en">Instructor1</lastName>

        <fullName lang="el">Διδάσκων1</fullName>
        <fullName lang="en">Instructor1</fullName>
    </instructor>
    <instructor>
        <firstName lang="el">Διδάσκων2</firstName>
        <firstName lang="en">Instructor2</firstName>

        <lastName lang="el">Διδάσκων2</lastName>
        <lastName lang="en">Instructor2</lastName>

        <fullName lang="el">Διδάσκων2</fullName>
        <fullName lang="en">Instructor2</fullName>
    </instructor>

    <title lang="el">Course 1</title>
    <title lang="en">Μάθημα 1</title>

    <url>http://eclass</url>

    <code lang="el">TMA1</code>

    <level>doctoral</level>

    <yearOfStudy>3</yearOfStudy>
    <semester>6</semester>

    <type>compulsory</type>

    <credithours>10</credithours>

    <coTeaching>true</coTeaching>
    <coTeachingColleagueOpensCourse>true</coTeachingColleagueOpensCourse>
    <coTeachingAutonomousDepartment>true</coTeachingAutonomousDepartment>
    <coTeachingDepartmentCreditHours>10</coTeachingDepartmentCreditHours>

    <language lang="en">greek</language>

    <targetGroup lang="el">Ομάδα στόχος.</targetGroup>
    <targetGroup lang="en">Just a target group.</targetGroup>

    <credits>30</credits>

    <description lang="el">Περιγραφή μαθήματος.</description>
    <description lang="en">Just a description.</description>
    <contents lang="el">Περιεχόμενα μαθήματος</contents>
    <objectives lang="el">Course objectives</objectives>
    <keywords lang="el">λέξη1, λέξη2</keywords>
    <keywords lang="en">keyword3, keyword4</keywords>
    <featuredBooks lang="el">Συγγράματα</featuredBooks>
    <prerequisites lang="el">Προαπαιτούμενα</prerequisites>
    <literature lang="el">Βιβλιογραφία</literature>

    <numberOfUnits>0</numberOfUnits>

    <thematic lang="el">Θεματική επιστημονική περιοχή</thematic>
    <thematic lang="en">Thematic scientific area</thematic>

    <institution lang="el">Ίδρυμα</institution>
    <institution lang="en">Institution</institution>
    <institutionDescription lang="el">περιγραφή</institutionDescription>
    <institutionDescription lang="en">description</institutionDescription>
    <department lang="el">Τμήμα</department>
    <department lang="en">Department</department>
    <sector lang="el">Τομέας</sector>
    <sector lang="en">Sector</sector>
    <curriculumTitle lang="el">Τίτλος ΠΣ</curriculumTitle>
    <curriculumTitle lang="el">title</curriculumTitle>
    <curriculumDescription lang="el">Περιγραφή ΠΣ</curriculumDescription>
    <curriculumDescription lang="en">Description</curriculumDescription>
    <outcomes lang="el">Μαθησιακά αποτελέσματα</outcomes>
    <outcomes lang="en">Learning Outcomes</outcomes>
    <curriculumKeywords lang="el">λέξη1, λέξη2</curriculumKeywords>
    <curriculumKeywords lang="en">keyword3, keyword4</curriculumKeywords>
    <curriculumLevel>doctoral</curriculumLevel>
    <curriculumTargetGroup lang="el">Ομάδα Στόχος</curriculumTargetGroup>
    <curriculumTargetGroup lang="en">Target Group</curriculumTargetGroup>
</course>
